services:
  youtube-download:
    container_name: youtube-download
    build: .
    ports:
      - "12498:12498"
    environment:
      - FLASK_ENV=production
    volumes:
      - type: bind
        source: ./audio
        target: /app/audio
      - type: bind
        source: ./video
        target: /app/video
      - type: bind
        source: ./tmp
        target: /app/tmp
    restart: unless-stopped
    networks:
      - traefik_network
    labels:
      traefik.enable: false
      glance.name: Youtube-Download
      glance.url: https://youtube.com
      glance.hide: false

networks:
  traefik_network:
    external: true
